[package]
name = "dusk_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full", "tracing"] }
anyhow = { version = "1.0", features = ["backtrace"] }
tracing = "0.1.37"
console-subscriber = "0.1.8"
tracing-subscriber = "0.3.16"
clap = { version = "4.1.6", features = ["derive"] }
wild = "2.1.0"
argfile = "0.1.5"
shellfish = { version = "0.8.0", features = ["app", "async", "rustyline"] }
rustyline = "11.0.0"
colored = "2.0.4"
