apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: dusk-stack
resources:
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - network-policy.yaml
configMapGenerator:
  - name: dawn
    files:
      - dawn.toml
