apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dawn
  labels:
    app.kubernetes.io/name: dawn
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dawn
