apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vector
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vector
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: otel-collector
      ports:
        - protocol: TCP
          port: 9598
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: clickhouse
      ports:
        - protocol: TCP
          port: 8123
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ceph
      ports:
        - protocol: TCP
          port: 8080
