apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper-headless
  labels:
    app.kubernetes.io/name: clickhouse-keeper
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: clickhouse-keeper
  ports:
    - name: client
      port: 9181
      targetPort: client
    - name: raft
      port: 9234
      targetPort: raft
