[package]
name = "dusk_py"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.27.0", features = ["experimental-async", "extension-module"] }
tokio = { version = "1.47.1", features = ["full"] }
dusk_connection = { path = "../dusk_connection" }
dusk_capnp = { path = "../dusk_capnp" }
dusk_program = { path = "../dusk_program" }
dusk_program_sh = { path = "../../../base/sh", features = ["client"] }
capnp = "0.21.5"
tracing = "0.1.41"
capnp-rpc = "0.21.0"
serde-pickle = "1.1"
