[package]
name = "dusk_py"
version = "0.1.0"
edition = "2021"


[lib]
name = "dusk"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["experimental-async", "extension-module"] }
tokio = { version = "1.47.1", features = ["full"] }
dusk_shell = { path = "../dusk_shell" }
dusk_capnp = { path = "../dusk_capnp" }
dusk_program = { path = "../dusk_program" }
dusk_program_sh = { path = "../../../programs/sh", features = ["client"] }
anyhow = "1.0"
capnp = "0.21.5"
capnp-rpc = "0.21.0"
serde-pickle = "1.1"
