[package]
name = "dusk_program_sh"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.0"
capnp = { version = "0.18.0", default-features = false, features = ["alloc"] }
capnp-rpc = { version = "0.18.0", default-features = false } 
anyhow = { version = "1.0.75", default-features = false }
dusk_capnp = { path = "../../dusk/src/dusk_capnp/" }

[build-dependencies]
capnpc = { version = "0.18.0", default-features = false }
dusk_capnp = { path = "../../dusk/src/dusk_capnp/" }
