[package]
name = "dusk_program_sh"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true}
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_core = { path = "../../dusk/src/dusk_core/", public = true }
slab = { version = "0.4.11", public = true }
linkme = { version = "0.3", optional = true, public = true }
# Declared for macro use, versions taken from dusk_program
capnp = { version = "*", public = false }

[build-dependencies]
dusk_capnp = { path = "../../dusk/src/dusk_capnp/"}

[features]
client = ["linkme"]
