apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: signoz
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: signoz
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: signoz-dashboards
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: clickhouse
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
      ports:
        - protocol: TCP
          port: 9092
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: signoz-dashboards
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: signoz-dashboards
  policyTypes: [Ingress, Egress]
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: signoz
              app.kubernetes.io/component: signoz
      ports:
        - protocol: TCP
          port: 8080
