repos:
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
      -   id: fmt
      -   id: cargo-check
      -   id: clippy
  -   repo: local
      hooks:
      -   id: cargo-nextest
          name: test
          entry: cargo nextest run --release 
          language: system
          pass_filenames: false
          types: [rust]

fail_fast: true
