[workspace]
members = [
    "artifacts/dusk_cli",
    "artifacts/dusk_impl",
    "artifacts/dusk_py",
    "dusk/src/dusk_capnp",
    "dusk/src/dusk_cli",
    "dusk/src/dusk_core",
    "dusk/src/dusk_program",
    "dusk/src/dusk_program_proc",
    "dusk/src/dusk_prompt",
    "dusk/src/dusk_py",
    "dusk/src/dusk_shell",
    "impls/nix",
    "programs/kill",
    "programs/init",
    "programs/ps",
    "programs/sh",
    "tests/cli",
    "tests/common",
    "tests/py",
]
resolver = "2"
