[project]
name = "dusk"
version = "0.1.0"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "maturin>=1.10.2",
    "pre-commit>=4.3.0",
]
dynamic = ["version"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "dusk/src/dusk_py/Cargo.toml"
module-name = "dusk"
python-source = "."
include = ["dusk/__init__.py"]
exclude = ["dusk/src/**"]

[tool.uv.workspace]
members = [
    "docs",
]
