[package]
name = "dusk_node"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = ["impl_nix"]
impl_nix = ["dep:dusk_nix"]
impl_std = ["dep:dusk_std"]
impl_windows = ["dep:dusk_windows"]

[dependencies]
dusk_nix = { path = "../../../impls/nix", optional = true }
dusk_std = { path = "../../../impls/std", optional = true }
dusk_windows = { path = "../../../impls/windows", optional = true }

dusk_capnp = { path = "../../../dusk/src/dusk_capnp/", public = true }
dusk_program = { path = "../../../dusk/src/dusk_program/" }
dusk_base = { path = "../../../dusk/src/dusk_base" }
dusk_program_sh_compiler_proc = { path = "../../../base/sh/compiler/proc" }
dusk_program_logs = { path = "../../../base/logs" }
