[package]
name = "dusk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.71"
embassy-executor = { version = "*", features = ["log", "nightly"] }
embassy-sync = { version = "*", features = ["log"] }
embassy-time = { version = "*", features = ["log"] }
log = "0.4.21"
static_cell = "2.1.0"
capnp = { version = "0.19.3", default-features = false, features = ["alloc"] }
capnp-rpc = { version = "0.19.0", default-features = false }
futures = { version = "0.3.31", default-features = false }
anyhow = { version = "1.0.95", default-features = false }
lazy_static = { version = "1.5.0", features = ["spin_no_std"]}

dusk_capnp = { path = "../dusk_capnp/" }
dusk_program = { path = "../dusk_program/" }
