apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ceph-init
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ceph-init
  policyTypes: [Ingress, Egress]
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ceph
      ports:
        - protocol: TCP
          port: 8080
