apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: dusk
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    replicated:
      size: 3
  preservePoolsOnDelete: true
  allowUsersInNamespaces:
    - dusk
  gateway:
    port: 80
    instances: 2
    priorityClassName: system-cluster-critical
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        memory: 4Gi
