apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: twilight
  labels:
    app.kubernetes.io/name: twilight
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: twilight
