[template]
description = "A dusk program"
cargo_generate_version = ">=0.21.0"

[hooks]
pre = ["pre-generate.rhai"]

[placeholders.program-name]
type = "string"
prompt = "Program name (lowercase, e.g. 'myprogram'):"
regex = "^[a-z][a-z0-9_]*$"
