apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: step-ca
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: step-ca
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nightfall
      ports:
        - protocol: TCP
          port: 9000
  egress: []
