[package]
name = "nightfall"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "nightfall"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0", public = true }
metrics = "0.24"
nightfall_membrane = { path = "membrane", public = true }
nightfall_provisioning = { path = "provisioning", public = true }
rand = "0.9"
tracing = "0.1.41"
