[package]
name = "nightfall"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "nightfall"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0", public = true }
arc-swap = { version = "1.7", public = true }
capnp = "0.21.7"
capnp-rpc = "0.21.0"
dusk_capnp = { path = "../../dusk/src/dusk_capnp" }
futures = "0.3"
jsonschema = { version = "0.58", default-features = false }
libc = "0.2"
metrics = "0.24"
nightfall_ledger = { path = "ledger", public = true }
nightfall_membrane = { path = "membrane", public = true }
nightfall_provisioning = { path = "provisioning", public = true }
rand = "0.9"
rdkafka = { version = "0.39", default-features = false, features = ["cmake-build", "curl-static", "ssl-vendored", "tokio", "zstd"], public = true }
ring = "0.17"
rustls = { version = "0.23", default-features = false, features = ["logging", "ring", "std", "tls12"], public = true }
rustls-pki-types = { version = "1.12", features = ["std"], public = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", public = true }
time = { version = "0.3.41", features = ["formatting", "parsing"] }
tokio = { version = "1.47", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"], public = true }
tokio-util = { version = "0.7", features = ["compat"], public = true }
toml = { version = "0.9", public = true }
tracing = "0.1.41"
uuid = { version = "1.17", features = ["v4", "v7"] }
x509-parser = "0.18"

[dev-dependencies]
jsonschema = { version = "0.58", default-features = false, features = ["resolve-file"] }
rcgen = { version = "0.14", default-features = false, features = ["crypto", "pem", "ring", "x509-parser"] }
tempfile = "3"
