[package]
name = "dusk_program_ps"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true}
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_program_proc = { path = "../../dusk/src/dusk_program_proc", public = true }
slab = { version = "0.4.11", public = true }
anyhow = { version = "1.0.88", public = true }
dusk_program_sh = { path = "../sh", public = true }
# Declared for macro use, versions taken from dusk_program
capnp = { version = "*", public = false }
linkme = { version = "*", optional = true, public = false }
clap = { version = "4", features = ["derive"], optional = true }

[build-dependencies]
dusk_capnp = { path = "../../dusk/src/dusk_capnp/"}

[features]
client = ["linkme", "dusk_program_sh/client", "clap"] 
