[package]
name = "nightfall_provisioning"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
base64 = "0.22"
dusk_capnp = { path = "../../../dusk/src/dusk_capnp", public = true }
dusk_program_nightfall = { path = "../../../base/nightfall", public = true }
hex = "0.4"
metrics = "0.24"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls-no-provider"] }
ring = "0.17"
rustls = { version = "0.23", default-features = false, features = ["logging", "ring", "std", "tls12"], public = true }
rustls-pki-types = { version = "1.12", features = ["std"], public = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", public = true }
thiserror = "2"
time = { version = "0.3.41", features = ["formatting", "macros"] }
tokio = { version = "1.47.1", features = ["sync", "time"] }
toml = "0.9"
tracing = "0.1.41"
uuid = { version = "1.17", features = ["v7"] }
webpki = { package = "rustls-webpki", version = "0.103", default-features = false, features = ["ring", "std"] }
x509-parser = { version = "0.18", features = ["verify"] }

[dev-dependencies]
rcgen = { version = "0.14", default-features = false, features = ["crypto", "pem", "ring", "x509-parser"] }
