[package]
name = "dusk_program_sh"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
tracing = { version = "0.1.41", default-features = false }
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true}
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
embassy-executor = { version = "0.10.0", features = ["nightly"] }
dusk_program_proc = { path = "../../dusk/src/dusk_program_proc", public = true }
dusk_core = { path = "../../dusk/src/dusk_core/", public = true }
slab = { version = "0.4.11", public = true }
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher"] }
linkme = { version = "0.3", optional = true, public = true }
# Declared for macro use, versions taken from dusk_program
capnp = { version = "0.21", public = false }
clap = { version = "4", features = ["derive"], optional = true }
dusk_program_sh_proc = { path = "proc", optional = true }
dusk_program_sh_compiler = { path = "compiler", optional = true, public = true }
tokio = { version = "1.47.1", features = ["full", "tracing"], optional = true, public = true }
reedline = { version = "0.47", features = ["sqlite", "idle_callback"], optional = true, public = true }
crossterm = { version = "0.29", optional = true }
nu-ansi-term = { version = "0.50.1", optional = true }
nu-table = { version = "0.107.0", optional = true }
nu-color-config = { version = "0.107.0", optional = true }
nu-protocol = { version = "0.107.0", optional = true }
termimad = { version = "0.20", optional = true, public = true }
colored_json = { version = "5.0.0", optional = true }
chrono = { version = "0.4.42", optional = true }
unicode-width = { version = "0.2", optional = true }
base64 = { version = "0.22.1", optional = true }
dusk_llm = { path = "../../dusk/src/dusk_llm", optional = true }
nix = { version = "0.30.1", features = ["hostname"], optional = true }

[build-dependencies]
dusk_build = { path = "../../dusk/src/dusk_build" }

[features]
client = [
    "linkme",
    "clap",
    "dusk_program_sh_proc",
    "dusk_program_sh_compiler",
    "tokio",
    "reedline",
    "crossterm",
    "nu-ansi-term",
    "nu-table",
    "nu-color-config",
    "nu-protocol",
    "termimad",
    "colored_json",
    "chrono",
    "unicode-width",
    "base64",
    "dusk_llm",
    "nix",
]
