[package]
name = "dusk_program_init"
version = "0.1.0"
edition = "2024"

[dependencies]
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true}
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_program_proc = { path = "../../dusk/src/dusk_program_proc", public = true }
dusk_core = { path = "../../dusk/src/dusk_core/" }
dusk_program_kvs_internal = { path = "../kvs/internal" }
async-io = "2.6.0"
futures = { version = "0.3.31", features = ["async-await"] }
tracing = { version = "0.1.41", default-features = false }
# Declared for macro use, versions taken from dusk_program
capnp = { version = "0.21", public = false }

[build-dependencies]
dusk_build = { path = "../../dusk/src/dusk_build" }

[features]
client = ["dusk_program_kvs_internal/client"]
