[package]
name = "dusk_core"
version = "0.1.0"
edition = "2024"

[dependencies]

# Declared for macro use, versions taken from dusk_program
async-trait = "*"
embassy-executor = "*"
embassy-futures = "*"
embassy-time = "*"

tracing = { version = "0.1.41", default-features = false }
static_cell = "2.1.1"
futures-io = { version = "0.3.31", default-features = false, public = true }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }

dusk_capnp = { path = "../dusk_capnp/", public = true}
dusk_program = { path = "../dusk_program/", public = true}
