apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bootstrap
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: bootstrap
  policyTypes: [Ingress, Egress]
  ingress: []
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
