[package]
name = "nightfall_membrane"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = { version = "1.0", public = true }
capnp = { version = "0.21.7", public = true }
capnp-rpc = { version = "0.21.0", public = true }
dusk_capnp = { path = "../../../dusk/src/dusk_capnp", public = true }
futures = "0.3"
hmac = "0.12"
metrics = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", public = true }
sha2 = "0.10"
tokio = { version = "1.47", features = ["rt", "time"] }
tokio-util = { version = "0.7", public = true }
toml = "0.9"
tracing = "0.1.41"
uuid = { version = "1.18", features = ["v7"] }

[build-dependencies]
dusk_capnp = { path = "../../../dusk/src/dusk_capnp" }

[dev-dependencies]
dusk_base = { path = "../../../dusk/src/dusk_base", features = ["client"] }
dusk_tests = { path = "../../../tests/common" }
nightfall_membrane = { path = ".", features = ["test-support"] }
tokio = { version = "1.47", features = ["io-util", "macros", "net", "rt", "time"] }
tokio-util = { version = "0.7", features = ["compat"] }

[features]
test-support = []
