[package]
name = "dusk_std"
version = "0.1.0"
edition = "2024"

[features]
default = ["hosted"]
hosted = ["critical-section/std", "embassy-executor/platform-std"]

[dependencies]
embassy-executor = { version = "0.10.0", default-features = false, features = ["trace", "nightly", "executor-thread"] }
embassy-time = { version = "0.5", features = ["std"] }
async-trait = "*"

dusk_core = { path = "../../dusk/src/dusk_core/" }
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_program_kvs_internal = { path = "../../base/kvs/internal" }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
critical-section = { version = "1" }
getrandom = "0.2"
tracing = { version = "0.1.41", default-features = false }
