apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nightfall
  labels:
    app.kubernetes.io/name: nightfall
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nightfall
