apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [nightfall, dawn, twilight, vector, otel-collector, kafka-init, signoz]
      ports:
        - protocol: TCP
          port: 9092
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
