[package]
name = "dusk_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
dusk_cli = { path = "../../dusk/src/dusk_cli" }
dusk_nix = { path = "../../impls/nix" }
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true}
dusk_program = { path = "../../dusk/src/dusk_program/" }
dusk_base = { path = "../../dusk/src/dusk_base" }
dusk_program_logs = { path = "../../base/logs", features = ["client"] }
dusk_shell = { path = "../../dusk/src/dusk_shell" }
dusk_program_sh = { path = "../../base/sh", features = ["client"] }
tokio = { version = "1", features = ["rt", "net", "sync", "time", "io-util"] }
capnp = "0.21"
capnp-rpc = "0.21"
serde_json = "1"
os_pipe = "1"
