[package]
name = "dusk_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
dusk_cli = { path = "../../dusk/src/dusk_cli" }
dusk_nix = { path = "../../impls/nix" }
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true}
dusk_program = { path = "../../dusk/src/dusk_program/" }
dusk_base = { path = "../../dusk/src/dusk_base" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.22", features = ["fmt"] }
