[package]
name = "dusk_nix"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.10.0", features = ["trace", "platform-std", "log", "nightly", "executor-thread"]}
async-trait = "*"

env_logger = "0.11.8"
nix = { version = "0.30.1", features = ["hostname", "time"] }
dusk_core = { path = "../../dusk/src/dusk_core/" }
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
lazy_static = { version = "1.5.0", features = ["spin_no_std"]}
critical-section = { version = "1", features = ["std"] }
rand = "0.8.5"
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.22", features = ["fmt", "chrono"] }