[package]
name = "dusk_nix"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.10.0", features = ["trace", "platform-std", "nightly", "executor-thread"]}
embassy-time = { version = "0.5", features = ["std"] }
async-trait = "*"

nix = { version = "0.30.1", features = ["hostname", "time", "feature"] }
dusk_core = { path = "../../dusk/src/dusk_core/" }
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_program_kvs_internal = { path = "../../base/kvs/internal" }
lazy_static = { version = "1.5.0", features = ["spin_no_std"]}
critical-section = { version = "1", features = ["std"] }
getrandom = "0.2"
tracing = { version = "0.1.41", default-features = false }
iana-time-zone = "0.1.65"

[target.'cfg(target_os = "linux")'.dependencies]
etc-os-release = "0.1.1"

[target.'cfg(target_os = "android")'.dependencies]
android_system_properties = "0.1.6"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
sysctl = "0.7.1"
