[package]
name = "dusk_base"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = "1.0"
dusk_program = { path = "../dusk_program", public = true }
dusk_program_cp = { path = "../../../base/cp", public = true }
dusk_program_date = { path = "../../../base/date", public = true }
dusk_program_echo = { path = "../../../base/echo", public = true }
dusk_program_false = { path = "../../../base/false", public = true }
dusk_program_hostname = { path = "../../../base/hostname", public = true }
dusk_program_init = { path = "../../../base/init", public = true }
dusk_program_kill = { path = "../../../base/kill", public = true }
dusk_program_kvs = { path = "../../../base/kvs", public = true }
dusk_program_logs = { path = "../../../base/logs", public = true }
dusk_program_nightfall = { path = "../../../base/nightfall", public = true }
dusk_program_programs = { path = "../../../base/programs", public = true }
dusk_program_ps = { path = "../../../base/ps", public = true }
dusk_program_sh = { path = "../../../base/sh", public = true }
dusk_program_sleep = { path = "../../../base/sleep", public = true }
dusk_program_true = { path = "../../../base/true", public = true }

[features]
client = [
    "dusk_program_cp/client",
    "dusk_program_date/client",
    "dusk_program_echo/client",
    "dusk_program_false/client",
    "dusk_program_hostname/client",
    "dusk_program_init/client",
    "dusk_program_kill/client",
    "dusk_program_kvs/client",
    "dusk_program_logs/client",
    "dusk_program_nightfall/client",
    "dusk_program_programs/client",
    "dusk_program_ps/client",
    "dusk_program_sh/client",
    "dusk_program_sleep/client",
    "dusk_program_true/client",
]
