apiVersion: v1
kind: ConfigMap
metadata:
  name: dawn-ingress-settings
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  host: dawn.dusk.example
  controllerNamespace: ingress-nginx
  controllerName: ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dawn
  labels:
    app.kubernetes.io/name: dawn
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  tls:
    - hosts: [dawn-host]
      secretName: dawn-ingress-tls
  rules:
    - host: dawn-host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dawn
                port:
                  name: https
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dawn-ingress
spec:
  secretName: dawn-ingress-tls
  commonName: dawn-host
  dnsNames: [dawn-host]
  duration: 720h
  renewBefore: 240h
  usages: [digital signature, server auth]
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: internal
    kind: Issuer
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: dusk-dawn-ingress
spec:
  allowed:
    commonName:
      value: dawn-host
      required: true
    dnsNames:
      values: [dawn-host]
      required: true
    usages: [digital signature, server auth]
  constraints:
    maxDuration: 720h
    privateKey:
      algorithm: ECDSA
      minSize: 256
      maxSize: 256
  selector:
    issuerRef:
      name: internal
      kind: Issuer
      group: cert-manager.io
    namespace:
      matchNames: [dusk]
