apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-clients
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [nightfall, dawn, twilight, vector, otel-collector, signoz]
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: dusk
              strimzi.io/kind: Kafka
      ports:
        - protocol: TCP
          port: 9093
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: strimzi
spec:
  podSelector:
    matchLabels:
      strimzi.io/cluster: dusk
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: dusk
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [twilight, grafana, signoz]
      ports:
        - protocol: TCP
          port: 5432
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: postgres
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: postgres
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8000
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: object-store-clients
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [dawn, vector, clickhouse, signoz, ceph-init]
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rook-ceph
          podSelector:
            matchLabels:
              app: rook-ceph-rgw
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
