nextest-version = "0.9.120"
experimental = ["setup-scripts"]

[scripts.setup.maturin-develop]
command = { command-line = "tests/scripts/maturin-develop.sh", relative-to = "workspace-root" }

[scripts.setup.dusk-cli-build]
command = { command-line = "tests/scripts/dusk-cli-build.sh", relative-to = "workspace-root" }

[[profile.default.scripts]]
filter = 'all()'
setup = ['dusk-cli-build', 'maturin-develop']
