apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ceph
  - ../../base/clickhouse
  - ../../base/dusk-gateway
  - ../../base/kafka
  - ../../base/otel-collector
  - ../../base/postgres
  - ../../base/step-ca
  - ../../base/vector

namespace: dev