[package]
name = "dusk_program_kvs"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true }
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_program_proc = { path = "../../dusk/src/dusk_program_proc", public = true }
dusk_program_kvs_internal = { path = "internal", public = true }
dusk_program_sh = { path = "../sh", public = true }
dusk_program_sh_proc = { path = "../sh/proc", optional = true }
dusk_core = { path = "../../dusk/src/dusk_core/" }
anyhow = { version = "1.0", public = true }
# Declared for macro use, versions taken from dusk_program
capnp = { version = "0.21", public = false }
linkme = { version = "0.3", optional = true, public = true }
tracing = { version = "0.1.41", default-features = false }
clap = { version = "4", features = ["derive"], optional = true }
tokio = { version = "1.47.1", features = ["net", "io-util", "rt", "time"], optional = true }

[build-dependencies]
dusk_build = { path = "../../dusk/src/dusk_build" }

[features]
client = [
    "linkme",
    "dusk_program_kvs_internal/client",
    "dusk_program_sh/client",
    "clap",
    "dusk_program_sh_proc",
    "tokio",
]
