apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: dusk-stack
resources:
  - statefulset.yaml
  - service.yaml
  - network-policy.yaml
configMapGenerator:
  - name: ceph-users
    files:
      - users.sh
