<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dusk</groupId>
  <artifactId>redis-compatibility-jedis</artifactId>
  <version>0</version>
  <dependencies>
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>8.0.1</version>
    </dependency>
  </dependencies>
</project>
