[package]
name = "dusk_prompt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.47.1", features = ["full", "tracing"], public = true }
tracing = "0.1.41"
shellfish = { version = "0.9.0", features = ["app", "async", "rustyline"] }
rustyline = "14.0.0"
colored = "2.2.0"
tokio-util = { version = "0.7.16", features = ["compat"]}
reedline = { version = "0.31.0", features = ["sqlite"], public = true}
crossterm = "0.27.0"
nu-ansi-term = "0.50.1"
nu-table = "0.107.0"
nu-color-config = "0.107.0"
nu-protocol = "0.107.0"
chrono = "0.4.42"
pretty-duration = "0.1.1"
capnp =  "0.21.5"
capnp-rpc = "0.21.0"
dusk_core = { path = "../dusk_core" }
dusk_capnp = { path = "../dusk_capnp", public = true }
dusk_shell = { path = "../dusk_shell", public = true }
linkme = { version = "0.3", optional = true, public = true }
dusk_program = { path = "../dusk_program/", public = true}
dusk_program_sh = { path = "../../../programs/sh", features = ["client"], public = true }
termimad = { version = "0.20", public = true}
colored_json = "5.0.0"
base64 = "0.22.1"
