logger:
  level: information
  console: 1
  formatting:
    type: json
listen_host:
  - "::"
  - 0.0.0.0
listen_try: 1
https_port: 8443
tcp_port_secure: 9440
openSSL:
  server:
    certificateFile: /etc/clickhouse-server/tls/tls.crt
    privateKeyFile: /etc/clickhouse-server/tls/tls.key
    disableProtocols: sslv2,sslv3,tlsv1,tlsv1_1
remote_servers:
  "@replace": "replace"
  dusk:
    shard:
      internal_replication: true
      replica:
        - host: clickhouse-0.clickhouse-headless.dusk.svc
          port: 9000
        - host: clickhouse-1.clickhouse-headless.dusk.svc
          port: 9000
macros:
  cluster: dusk
  shard: "01"
  replica:
    "@from_env": CLICKHOUSE_REPLICA_HOST
zookeeper:
  node:
    - host: clickhouse-keeper-0.clickhouse-keeper-headless.dusk.svc
      port: 9181
    - host: clickhouse-keeper-1.clickhouse-keeper-headless.dusk.svc
      port: 9181
    - host: clickhouse-keeper-2.clickhouse-keeper-headless.dusk.svc
      port: 9181
distributed_ddl:
  path: /clickhouse/task_queue/ddl
default_replica_path: /clickhouse/tables/{uuid}/{shard}
default_replica_name: "{replica}"
named_collections:
  lake:
    url:
      "@from_env": LAKE_URL
    access_key_id:
      "@from_env": LAKE_ACCESS_KEY_ID
    secret_access_key:
      "@from_env": LAKE_SECRET_ACCESS_KEY
    format: Parquet
