[package]
name = "dusk_program_nightfall"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dusk_capnp = { path = "../../dusk/src/dusk_capnp/", public = true }
dusk_program = { path = "../../dusk/src/dusk_program", public = true }
dusk_program_proc = { path = "../../dusk/src/dusk_program_proc", public = true }
dusk_program_sh = { path = "../sh", public = true }
dusk_program_sh_proc = { path = "../sh/proc", optional = true }
dusk_core = { path = "../../dusk/src/dusk_core/" }
anyhow = { version = "1.0", public = true }
async-io = "2.6.0"
futures = { version = "0.3.31", features = ["async-await"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
rcgen = { version = "0.14", default-features = false, features = ["crypto", "pem", "ring"] }
ring = "0.17"
x509-parser = "0.18"
tracing = { version = "0.1.41", default-features = false }
capnp = { version = "0.21", public = false }
linkme = { version = "*", optional = true, public = false }
clap = { version = "4", features = ["derive"], optional = true }

[build-dependencies]
dusk_build = { path = "../../dusk/src/dusk_build" }

[features]
client = ["linkme", "dusk_program_sh/client", "clap", "dusk_program_sh_proc"]
