[package]
name = "dusk_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dusk"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.47.1", features = ["full", "tracing"] }
anyhow = { version = "1.0", features = ["backtrace"] }
tracing = "0.1.41"
console-subscriber = "0.2.0"
tracing-subscriber = "0.3.20"
clap = { version = "4.5.47", features = ["derive"] }
wild = "2.2.1"
argfile = "0.2.1"
tokio-util = { version = "0.7.16", features = ["compat"]}
dusk_prompt = { path = "../dusk_prompt/" }

