apiVersion: v1
kind: ServiceAccount
metadata:
  name: dusk-pki
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dusk-pki
rules:
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [create]
  - apiGroups: [""]
    resources: [secrets]
    resourceNames:
      - fleet-provisioner
      - step-ca-password
      - step-ca
      - pki-ca
      - fleet-server-ca
      - internal-ca
      - nightfall-fleet-tls
      - nightfall-provision-tls
      - nightfall-inner-tls
      - nightfall-admin-tls
      - dawn-tls
      - twilight-tls
      - admin-tls
    verbs: [get]
  - apiGroups: [""]
    resources: [secrets]
    resourceNames:
      - nightfall-fleet-tls
      - nightfall-provision-tls
      - nightfall-inner-tls
      - nightfall-admin-tls
      - dawn-tls
      - twilight-tls
      - admin-tls
    verbs: [update]
  - apiGroups: [""]
    resources: [configmaps]
    resourceNames: [dusk-trust-anchors]
    verbs: [get, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dusk-pki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dusk-pki
subjects:
  - kind: ServiceAccount
    name: dusk-pki
